### ISSUE TITLE
i2c communication

### ISSUE THREAD

**Issue by bigfatbrowncat** [cubieboard/CC-A80-kernel-source#3]
Hello!

I'm not sure this bug is posted to a proper repo. I think it's related to kernel, but I'm not an expert, sorry...

I'm trying to use a simple I2C controller with my Cubieboard 4 device using Ubuntu Linaro Server distro (version 2.0). 

In order to use the i2c-0 port I've connected the pins: 
VCC->13 (it needs 3.3V)
GND->14
SCK->4
SDA->6

I've installed libi2c-dev and i2c-tools. Right after that I checked if i2c devices are present in /dev. They appeared, but
1. Any try to use i2c tools (i2cdetect for instance) show error "could not open file /dev/i2c-0"
2. After reboot all devices /dev/i2c-* disappeared completely.

Do I do anything wrong? Maybe I should modify something in sys_config.fex (unfortunately the format for twi devices is different than any previous model and I can't find any tutorial).

Or maybe this feature hasn't been implemented yet?

**Comment by sunbeyond40** [comment]
The reason is the kernel_config  is  no enable.  The problem  have benn fixed in new SDK.   you just update the SDK and build.

# CONFIG_I2C_CHARDEV is not set
+CONFIG_I2C_CHARDEV=y

**Comment by bigfatbrowncat** [comment]
Thank you for rapid response!

I'm a newcomer (I've never built the kernel yet). Could you please provide me with some instructions or links?

And, by the way, when are you going to make a new Ubuntu Linaro release (with this bug fixed)?

**Comment by sunbeyond40** [comment]
Build kernel refer:   http://dl.cubieboard.org/model/cc-a80/Doc/ubuntu-linaro/Cubieboard4-Linux-Sdk-Guide.pdf
We just release 1.0 (not fixed this bug), Maybe we will not release another  one recently
